---
title: "Data Science Specialization"
author: "David Mukajanga"
date: "8/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This course is taken as a starting point to learning data science. It is a beginner course and in it we will learn what is data science about, why we should learn it (where we will use it) and start with the basics.  


# Module 1. Data Science Toolbox  
## Contents:  
1. Meaning of Data Science  
2. Data Science Process  
3. Data Science Tools  
4. Installing R & RStudio  
5. Version Control: Git & GitHub  
6. Types of Data Science Questions  

## Introduction:  
In this module we will look at the tools you need for Data Science. We will define what data science is and explain it's process along the way.  

## Meaning of Data Science  
The art of using data to answer scientific questions. Data science questions are the type of questions that can be answered by using statistical data analysis tools (A better definition is on the way).

## Data Science Process  
1. Formulating a scientific question.  
2. Getting the data that can answer that question.  
3. Analyzing the data.  
4. Presenting the findings and sharing them with the relevant audience.  
5. Referring the people who helped along the way.  

## Data Science Tools  
1. Platforms for asking help.  
2. Statistical languages and tools.  

### Platforms For Asking Help
* Coursera Community  
* Stack Overflow  
* Cross Validated  

##### Reasons Why Your Code Might Not Work  
* 90% of the time you would've made a mistake either in writting the code or choosing the method of analysis.  

##### Guidelines For Getting Help
1. Read the manuals  
2. Search the web  
3. If you are going to ask from a forum, first search the archives of the forum you plan to ask.  
4. Read the frequently asked questions.  
5. Ask a skilled fiend: This usually entails your classmates.  
6. Find an answer by inspection or experimentation.  
7. If you are an advanced programmer, read the source code.  

##### Guidelines In Asking Questions
1. Let other people know that you have done all the previous necessary steps.  
2. Read the documentation :) :), just be patient and read it.  
3. Describe the goal. This is more important than describing steps.  
4. Be explicit about your question.  
5. Provide as minimum amount of information as it possibly appropriate.  
6. Follow-up with the answer if/when you find it.  

## Installing R & RStudio  

### What is R?  
* It is a both a computer language and a programming program used for statistical analysis and at an advanced stage programming.  
* It is a derivative of another coding language called "S" which was developed in 1976 originally as an internal statistical analytical tool for a technological company called *Bell Technologies* but later adopted by the computer programming community as both a language for statistical analysis and programming.  
* The original goal of the creator of this language was to enable a statistician to be able to carry-out advanced statistical analysis on data without having the need to know any major computer programming language.  
* The goal is achieved as both "S" and later "R" became popular computer languages for statistical analysis. The syntax between the 2 languages is not different at all but R has got more functioning added onto it that makes it popular in the open source coding community.  

### What is RStudio
* It is a platform which makes using R simpler and more interactive, that is, enabling it to display tables, charts, graphs and other things.  

### How R and RStudio works?
* First you have to download R. The instructions for doing so are in the next heading.  
* Then you download RStudio.  
* Now you can use R without RStudio, just that your workflow will be so technical (just several lines of code) and less interactive (A.K.A Less fun).  
* The basic R installation comes with several tools that enable you to carry out statistical analysis right away but it doesn't contain all tools for statistical analysis. These missing tools are called **Packages**. They basically add functionality to R as a program and enable it to do more complicated stuff.  
* A good example of this is when you install a new operating system in your computer. The operating system might come with native programs for things like text editing and video playback but if you want serious functionality in say text editing, you will still have to download 3^{rd} party programs such as Microsoft Word and VLC Media Player. These third party programs are what Packages are in R.  
* R Packages are stored in cloud-based online databases called "Repositories". In this particular websites, R Packages can be downloaded and installed at any time free of cost.  
* Because R is an open source project, R Packages are developed and updated by an online open source community which means that anybody can create a new package and modify an existing one without any restrictions.  
* The open-source part of it also allows for problems within packages to be detectable quickly and also solved quickly as anyone with the ability to do so can do so.  
* The main 3 big repositories for R Packages are [CRAN](https://cran.r-project.org/web/packages/), [BioConductor (For BioInfo statistical packages)](https://bioconductor.org/packages/release/BiocViews.html#___Software), and GitHub (Which is not only specific for R). To know these is just a formality as installing R packages does not require you to visit these sites first.

### Download Sources:
  * Both two are free software so just type "R free download for Windows/Mac etc" in google and it should lead you to right places.  
  * The same goes for RStudio.  
  
### Tour of RStudio
  * The interface has four main quadrants/panels:
    1. Source = Top Left  
    2. Console = Bottom Left  
    3. Environment = Top Right  
    4. Files = Bottom Right  

  * The work flow is like the following:
    1. You input the code into the **CONSOLE** quadrant  
    2. It gets interpreted in the **ENVIRONMENT** quadrant  
    3. If the output not a plot it is shown in **SOURCE** quadrant. If it is a plot it is shown in the **Plots** tab of the **FILE** quadrant  
    4. The **FILES** quadrant in the bottom right will show you the folder in which all the files of your current project are saved. The **Packages** tab in the same quadrant will show all R packages that you have installed and will display also which are currently active via a green tick at a check box in the left side of the package name.    
    
  * To find the packages for any task you have in mind, there are 2 main ways:-  
    1. [rdocumentation.org](rdocumentation.org)  
    2. Google that task with "R package" at the end. Eg. "R package for statistical plots"
    
  * To install packages from BioConductor:  
    1. 1^{st} run this code:- source("https://bioconductor.org/bioclite.R")
       * This will make the main install function of Bioconductor: bioclite (), availabe to you.  
    2. Then you can install any package from Bioconductor like so:-
       * Bioclite ("Package Name Goes Here")  
      
  * Rare occasions:-
    - You might not find the package you are looking for in CRAN or Bioconductor.  
    - In such a case you'll need to install your package from GitHub. To do this:-  
      1. Find the package name **AND** the name of the author of the package you want from GitHUb.  
      2. Install the "devtools" package in R and load it.  
      3. Use the following command to install the package from GitHub:-
        * install_github ("author/package")
    
    








# Module 2: R Programming.

## Contents:  
1. Nuts and Bolts of R  
2. Control Structures, Functions, Scoping Rules, Dates and Times.  
3. Loop Functions, Debugging Tools.  
4. Simulation, Code Profiling.  

## 1. Nuts and Bolts of R.
### R Markdown
* It is a computer language that allows the user to write text and computer code in one file and be able to display both the text, the code and the output of the code in the final document.  
* R Markdown is important in the data science community since it enables easier communication from one data scientist to another by enabling them to see both the content of the research study and the steps taken to analyze findings both in the same file. This makes it easy if the other data scientist want to use the same steps to solve a similar problem.  
* It is also popular for it's ease of revision and editing and the fact that the final output can be printed in PDF, HTML, Web and many other useful formats.  
* It is also quite simple, with few symbols used for assigning headers, text formatting and specifying titles and codes in the document. The document containing instructions on what symbols are used to do what in R Markdown (A.K.A RMarkdown Cheat Sheet) is found [here](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf).  
* To open a new RMarkdown file in RStudio, go to File > New File > R Markdown..  
* A new window will appear asking you for the name of the document, author, date and whether you want to save it in PDF, HTML or PowerPoint. Choose your settings and a new tab will open in the source quadrant of RStudio with the name of your file and a ".Rmd" file extension. You are good to go.  
* After writing on your file, you can save the contents by clicking on the saving disk icon at the source panel of your Rstudio session. This will save what you have written so far but will not print the final output in the format you specified e.g. PDF, PowerPoint etc.  
* To do this, find a knitting icon in the source panel or click "Ctrl + Shift + K" if you are using windows. More instructions are provided in the RMarkdown cheat sheet attached above.  


### Nuts and Bolts of R
If you are working directly from R without RStudio, the first step is to set a **~~working~~** directory.  
* In windows, go to an open R-GUI and open file > change dir & then choose the location of the folder you want R to read and write from. For Mac users, please search the web :) :).  
* To know what is your working directory type this command in R console:- getwd()  






### R Input and Evaluation




### Data Types

##### R Objects & Attributes

##### Matrices

##### Factors

##### Missing Values

##### Data Frames

##### Name Attribute



### Reading Tabular Data Into R

**N.B** :- Before starting this part, please read [this page (Click on the words "this page")](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/read.table), and have it memorized.

* There are main two functions used to paste tabular data into R:-
  - read.table() : Used primarily for a tables that are on normal text files .i.e. MS Word etc.
  - read.csv() : Used primarily for data that has been inputed in a spreadsheet or saved in a similar file structure.  
  
* Depending on the size of your dataset, you might or might not need to attach the following attributes into your read.table/csv function. These attributes specify for R the number of rows in the data, the class of elements in the table & so on so that R doesn't need to carryout those calculations by itself. This is very handy when you are handling big data because if you don't tell R these attributes of your data, it will eat a whole chunk of your time counting them and in the process slow you down.  

* It is also necessary for you to count and know these attributes about your data if you are working with big data because they will enable you to know if you have a large enough RAM to print that data into R or not. This is because, by default, R stores all the tables that you import into it in the RAM of the computer. So if, for example, printing your data set into R will require 3GB of your RAM while your computer has only two, you will not be able to do anything with that data through R.  

* It will also assist you on deciding how many application you will need open during that analysis as all applications also use RAM to store temporary data into them. In the above example, even if your computer had 4GB of RAM, you will still be having a hard time doing that particular analysis since an operating system like windows 10 itself uses at least 1GB in it's operations. If your R takes the remaining 3GB then the performance of that analysis will be considerably slow.  

* Let's take an example of a moderately large data set with 1.5 million rows and 120 columns. To get the amount of RAM needed for this analysis, we will do the following calculation:-  
  1. The Number of Elements x The number of Bytes to store each element.
    * No. of Elements = 1.5mil x 120.
    * Assuming all elements are numeric, the standard storage is 8 bytes per numeric.  
    Hence:- 1.5mil x 120 x 8 = 1.44 billion Bytes.
    - 1 GB = 1 Billion Bytes
    - 1.44 Billion Bytes = 1.44 GB.  
    
* Now although the calculated amount is 1.44GB, it is usually recommended to count double the amount to account for a smoother operation. So in our example, we will need not less that 3GB to run our analysis smoothly, not accounting for the influence of other software that may be running at the time.  

* But if you are doing an analysis on a small or medium data set, say with a 1000 or less rows, you need not trouble yourself with specifying to R the classes of data or other attributes in the table. It will do the work itself and it won't take long.  

* The arguments in question are following:-  
  * colClasses"" :- This indicates the class of data in each column in the dataset. It is super useful in big data because specifying this saves you a lot of time and processing requirement that would take R to do this by default.  
  * nrow"" :- Also super useful in terms of memory as it will tell R outrightly how many rows are there thus making it easier to calculate the amount of storage needed rather than keeping quiet. You can roughly overestimate the number, R will still count the right number of rows in the end.  
  * skip"" :- It will tell R the number of rows to skip from the beginning.  
  * Sep"" :- This indicates how columns are separated.  
  * StringAsFactors :- You use this when you want to code character variables as factors.  
  * File :- This tells the name fo a file or connection.  
  * Header :- This is a logical indicating that the table has a header line.  
  * Comment.char :- A character string indicating the comment character.  
  
  
* It is usually advisable to make sure that here are no comments on your data set. You can account for this by using the "comment.char" argument but it is just good practice to remove comments from a data set.  



### Textual Data Format

* This is a way of saving a data set such that the metadata concerning that data set, data like the class of elements in a column, number of rows etc also gets saved with the file.  

* The data is saved not necessarly in a tabular form but as a sort of textual data that can be read back to R with all the metadata instructions intact. The metadata instruction is saved as a code so when you read in back into R, those instructions concerning number of rows and classes of data get executed directly without the need for you to re-specify anything from the beginning.  

* The function to create that kind of data is called: dput () or dump (); while the function to read that kind of data is called "dget ()".  

* The difference between dput() and dump() is that dput () is only used for encoding one R object/table while dump() can be used for multiple R objects.

* Dump-ing or dput-ting is useful in saving data that might have originally been in an excel format etc, as an R readable text file and include that metadata instruction that is very important.  

* Another benefit is the ability of fixing the problem if there has been a corruption in the data. This makes the data saved this way more long living.  
 

* The only down side of saving files this way is that they eat a lot of space and generally need to be compressed.  


### Connections: Interfaces to The Outside World

